### ISSUE TITLE
PiT 23.3: frontend does not compile

### ISSUE THREAD

**Issue by manolo** [vaadin/skeleton-starter-flow-spring#891]
When compiling the project with `23.3.0.alpha2` it does not compile, though, it compiles with `23.3.0.alpha1`

- Clone the project, update vaadin version, and run it in dev-mode
```
git clone https://github.com/vaadin/skeleton-starter-flow-spring.git 
cd skeleton-starter-flow-spring
mvn -B -q versions:set-property -Dproperty=vaadin.version -DnewVersion=23.3.0.alpha2
mvn
```
- There is an error in console
```
ERROR(TypeScript)  Cannot find module '@vaadin/flow-frontend/Flow' or its corresponding type declarations.
FILE  /Users/manolo/Github/platform/platform-in-test-script/tmp/skeleton-starter-flow-spring/frontend/index.ts:1:20
 > 1 | import {Flow} from '@vaadin/flow-frontend/Flow';
     |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   2 | import {Router} from '@vaadin/router';
   3 |
   4 | const {serverSideRoutes} = new Flow({
```
- Compile in production 
```
mvn -Pproduction -DskipTests
```
- Error in console
```
[ERROR] vite v3.2.4 building for production...
[ERROR] transforming...
[ERROR] frontend/index.ts(1,20): error TS2307: Cannot find module '@vaadin/flow-frontend/Flow' or its corresponding type declarations.
```

**Comment by manolo** [comment]
Fixed in https://github.com/vaadin/flow/pull/15247
